export const dataSource = [
  {
    id: 1,
    params: 'buttonApi',
    description: '添加 Tag 的按钮组件的控制属性',
    type: 'Object',
    defaultValue: '{ }',
  },
  {
    id: 2,
    params: 'editable',
    description: '标签是否可以编辑/修改',
    type: 'Boolean',
    defaultValue: 'true',
  },
  {
    id: 3,
    params: 'inputApi',
    type: 'Object',
    description: '添加/编辑 Tag 的文本输入组件的 api',
    defaultValue: '{}',
  },
  {
    id: 4,
    params: 'maxLength',
    description: '标签文本显示的最大字数, 多余文本用省略号表示，完整文本用 ToolTip 显示',
    type: 'Number',
    defaultValue: '10',
  },
  {
    id: 5,
    params: 'onChange',
    description: '回调修改后的 Tag 标签',
    type: 'Func',
    defaultValue: '() => {}',
  },
  {
    id: 6,
    params: 'tags',
    description: '标签数组',
    type: 'Array',
    defaultValue: '[ ]',
  },
  {
    id: 7,
    params: 'tagApi',
    description: 'Tag 组件的控制属性',
    type: 'Object',
    defaultValue: '{ }',
  },
]