export const dataSource = [
  {
    id: 1,
    params: 'text',
    description: '水印文本-内容',
    type: 'String',
    defaultValue: 'canvas',
  },
  {
    id: 2,
    params: 'textAlign',
    type: 'Number',
    description: '水印文本-对其方式',
    defaultValue: 'middle',
  },
  {
    id: 3,
    params: 'textRotate',
    type: 'Number',
    description: '水印文本-旋转角度',
    defaultValue: '-20',
  },
  {
    id: 4,
    params: 'fontColor',
    type: 'String',
    description: '水印文本-颜色',
    defaultValue: '#000',
  },
  {
    id: 5,
    params: 'fontFamily',
    type: 'String',
    description: '水印文本-字体',
    defaultValue: 'Arial',
  },
  {
    id: 6,
    params: 'fontSize',
    type: 'Number',
    description: '水印文本-大小',
    defaultValue: '20',
  },
  {
    id: 7,
    params: 'fontShadowColor',
    type: 'String',
    description: '文本阴影颜色',
    defaultValue: 'rgba(0, 0, 0, 0.5)',
  },
  {
    id: 8,
    params: 'fontShadowOffsetX',
    type: 'Number',
    description: '文本阴影 x 偏移',
    defaultValue: '3',
  },
  {
    id: 9,
    params: 'fontShadowOffsetY',
    type: 'Number',
    description: '文本阴影 y 偏移',
    defaultValue: '3',
  },
  {
    id: 10,
    params: 'fontShadowBlur',
    description: '轻微模糊阴影',
    type: 'Number',
    defaultValue: '3',
  },
  {
    id: 11,
    params: 'backgroundColor',
    description: '背景颜色',
    type: 'String',
    defaultValue: '#fff',
  },
  {
    id: 12,
    params: 'maskWidth',
    description: '生成图像宽度',
    type: 'Number',
    defaultValue: '200',
  },
  {
    id: 13,
    params: 'maskHeight',
    description: '生成图像高度',
    type: 'Number',
    defaultValue: '100',
  },
  {
    id: 14,
    params: 'maskOpacity',
    description: '生成图像透明度',
    type: 'Number',
    defaultValue: '1',
  },
  {
    id: 15,
    params: 'style',
    description: '水印 css 样式',
    type: 'Object',
    defaultValue: '{ }',
  },
]