export const dataSource = [
  {
    id: 1,
    params: 'formCols',
    description: '表单组一行显示表单元素的个数',
    type: 'Number',
    defaultValue: '1',
  },
  {
    id: 2,
    params: 'formConfigs',
    description: '表单配置数组',
    type: 'Array',
    defaultValue: '必填',
  },
  {
    id: 3,
    params: 'formlayout',
    description: '表单布局类型, 仅支持 antd 提供的表单布局 horizontal vertical inline 三种',
    type: 'String',
    defaultValue: 'horizontal',
  },
  {
    id: 4,
    params: 'formValues',
    description: '整个表单值',
    type: 'Object',
    defaultValue: '必填',
  },
  {
    id: 5,
    params: 'formItemClassName',
    description: '表单元素附加的 css 类',
    type: 'String',
    defaultValue: '空',
  },
  {
    id: 6,
    params: 'formItemStyle',
    description: '表单元素附加的 css 样式',
    type: 'Object',
    defaultValue: '{}',
  },
  {
    id: 7,
    params: 'formItemLayout',
    description: '表单元素栅格布局，当表单为 horizontal 布局时，设置表单元素的 label 元素和 表单输入区域的栅格布局，值为 antd 提供的栅格布局, 或内置的栅格布局映射值(L1,L2,L3,L4,L5,L6,L7)',
    type: 'Object/String',
    defaultValue: '-',
  },
  {
    id: 8,
    params: 'formItemSpace',
    description: '表单元素水平间隔距离',
    type: 'Number',
    defaultValue: '0',
  },
  {
    id: 9,
    params: 'onChange',
    description: '可控表单搜集表单值的事件方法，绑定到 onChange/onBlur 事件',
    type: 'Func',
    defaultValue: '必填',
  },
]